d=set(["ooty","ballari","banglore","chennai"])
print("\n printing the original set...")
print(d)
print("\n adding some d from the set...")
d.add("hampi")
print(d)
print("\n removing some d from the set...")
d.remove("ballari")
print(d)